name: Deploy SQL Database with Reusable Workflow

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    uses: ./.github/workflows/sql-template.yml
    with:
      environment: development
      sql_server: "rnjtb-41-13-228-53.a.free.pinggy.link,36679"
      sql_user: "Auto_user"
      sql_password: "StrongPassword123!"

  deploy-prod:
    needs: deploy-dev
    uses: ./.github/workflows/sql-template.yml
    with:
      environment: production
      sql_server: "rnnmh-41-13-228-53.a.free.pinggy.link,38629"
      sql_user: "Auto_user"
      sql_password: "qwerty"
