name: Deploy SQL Database with Multi-Environment Workflow

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    uses: ./.github/workflows/sql-deployment.yml
    with:
      sql_server: ${{ secrets.DEV_SQL_SERVER }}
      sql_user: ${{ secrets.DEV_SQL_USER }}
      sql_password: ${{ secrets.DEV_SQL_PASSWORD }}
      database_name: AutoDBOngeziwe
      environment_name: Development
