name: Deploy SQL Database with Multi-Environment Workflow

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    uses: ./.github/workflows/sql-deployment.yml
    with:
      sql_server: "rnnmh-41-13-228-53.a.free.pinggy.link,38629"
      sql_user: "Auto_user"
      sql_password: "StrongPassword123!"
      database_name: AutoDBOngeziwe
      environment_name: Development
