name: Deploy SQL Database with Reusable Workflow

on:
  workflow_dispatch:

jobs:
  deploy-dev:
    uses: ./.github/workflows/sql-template.yml
    with:
      environment: development
      sql_server: ${{ secrets.DEV_SQL_SERVER }}
      sql_user: ${{ secrets.DEV_SQL_USER }}
      sql_password: ${{ secrets.DEV_SQL_PASSWORD }}

  deploy-prod:
    needs: deploy-dev
    uses: ./.github/workflows/sql-template.yml
    with:
      environment: production
      sql_server: ${{ secrets.PROD_SQL_SERVER }}
      sql_user: ${{ secrets.PROD_SQL_USER }}
      sql_password: ${{ secrets.PROD_SQL_PASSWORD }}
