name: Deploy SSIS Packages to SSISDB

on:
  workflow_dispatch:

jobs:
  deploy-ssis:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Locate and deploy SSIS .ispac file
        run: |
          ISPAC_PATH="HandsOnProjects/Timesheet/Packages/Integration Services Project2/bin/Development/Integration Services Project2.ispac"
          PROJECT_NAME="Integration Services Project2"
          FOLDER_NAME="Timesheet"
          DEPLOY_SERVER="LAPTOP-938SNHB2\MSSQLSERVER01"  
          DEPLOY_USER="${{ secrets.SQL_USER }}"
          DEPLOY_PASS="${{ secrets.SQL_PASSWORD }}"

          # Optional: echo a message before deploying
          echo "Deploying SSIS project to SSISDB..."

          # Run the ISDeploymentWizard silently
          "C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\ISDeploymentWizard.exe" ^
            /Silent ^
            /ModelType:Project ^
            /SourcePath:"$ISPAC_PATH" ^
            /DestinationServer:"$DEPLOY_SERVER" ^
            /DestinationPath:"SSISDB\$FOLDER_NAME\$PROJECT_NAME" ^
            /SQLEXPRESS ^
            /UserName:"$DEPLOY_USER" ^
            /Password:"$DEPLOY_PASS"
