name: Deploy SSIS Packages to SSISDB

on:
  workflow_dispatch:

jobs:
  deploy-ssis:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy SSIS .ispac to SSISDB
        shell: pwsh
        run: |
          # Allow script execution
          Set-ExecutionPolicy Bypass -Scope Process -Force

          # Define variables
          $ispacPath = "$env:GITHUB_WORKSPACE/HandsOnProjects/Timesheet/Packages/Integration Services Project2/bin/Development/Integration Services Project2.ispac"
          $folderName = "Automation"
          $projectName = "Integration Services Project2"
          $destinationServer = "LAPTOP-938SNHB2\SQLSERVER_2025"
          $destinationPath = "/SSISDB/$folderName/$projectName"

          Write-Host "Starting SSIS deployment..."
          Write-Host "ISPAC Path: $ispacPath"
          Write-Host "Deploying to: $destinationPath"

          # Use ISDeploymentWizard to deploy
          & "C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\ISDeploymentWizard.exe" `
            /Silent `
            /ModelType:Project `
            /SourcePath:"$ispacPath" `
            /DestinationServer:"$destinationServer" `
            /DestinationPath:"$destinationPath"

          if ($LASTEXITCODE -ne 0) {
            Write-Error "SSIS deployment failed with exit code $LASTEXITCODE"
            exit 1
          } else {
            Write-Host "✅ SSIS deployment completed successfully."
          }
