name: Deploy SQL Database with Reusable Workflow

on:
  workflow_dispatch:

jobs:
  development:
    uses: ./.github/workflows/sql-template.yml
    with:
      environment: development
    secrets:
      sql_server: ${{ secrets.DEV_SQL_SERVER }}
      sql_user: ${{ secrets.DEV_SQL_USER }}
      sql_password: ${{ secrets.DEV_SQL_PASSWORD }}

  Production:
    needs: development
    uses: ./.github/workflows/sql-template.yml
    with:
      environment: production
    secrets:
      sql_server: ${{ secrets.PROD_SQL_SERVER }}
      sql_user: ${{ secrets.PROD_SQL_USER }}
      sql_password: ${{ secrets.PROD_SQL_PASSWORD }}
