name: Deploy SSIS Packages to SSISDB

on:
  workflow_dispatch:

jobs:
  deploy-ssis:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy SSIS .ispac to SSISDB
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force

          # Absolute path to the ISPAC file
          $ISPAC_PATH = "$env:GITHUB_WORKSPACE\HandsOnProjects\Timesheet\Packages\Integration Services Project2\bin\Development\Integration Services Project2.ispac"

          # Metadata
          $PROJECT_NAME = "Integration Services Project2"
          $FOLDER_NAME = "Automation"
          $DEPLOY_SERVER = "LAPTOP-938SNHB2\SQLSERVER_2025"

          Write-Host "Deploying SSIS project to SSISDB..."

          & "C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\ISDeploymentWizard.exe" `
            /Silent `
            /ModelType:Project `
            /SourcePath:"$ISPAC_PATH" `
            /DestinationServer:"$DEPLOY_SERVER" `
            /DestinationPath:"/SSISDB/Automation/Integration Services Project2"


          if ($LASTEXITCODE -ne 0) {
            throw " SSIS deployment failed with exit code $LASTEXITCODE"
          } else {
            Write-Host " SSIS deployment completed successfully."
          }
