name: Deploy AutoTest Database

on:
  push:
    branches:
      - main
    paths:
      - 'sql-scripts/**'  # Trigger when SQL scripts change

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy Setup Script
        uses: azure/sql-action@v2.3
        with:
          connection-string: 'Server=${{ secrets.SQL_SERVER }};User ID=${{ secrets.SQL_USER }};Password=${{ secrets.SQL_PASSWORD }};Initial Catalog=master;'
          path: 'sql-scripts/setup.sql'
          action: 'execute'

      - name: Deploy Contacts Script
        uses: azure/sql-action@v2.3
        with:
          connection-string: 'Server=${{ secrets.SQL_SERVER }};User ID=${{ secrets.SQL_USER }};Password=${{ secrets.SQL_PASSWORD }};Initial Catalog=AutoTest;'
          path: 'sql-scripts/add-contacts.sql'
          action: 'execute'