name: Deploy SSIS Packages to SSISDB

on:
  workflow_dispatch:

jobs:
  deploy-ssis:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy SSIS .ispac to SSISDB
        shell: powershell
        run: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force

          $ISPAC_PATH = "HandsOnProjects/Timesheet/Packages/Integration Services Project2/bin/Development/Integration Services Project2.ispac"
          $PROJECT_NAME = "Integration Services Project2"
          $FOLDER_NAME = "Timesheet"
          $DEPLOY_SERVER = "LAPTOP-938SNHB2\MSSQLSERVER01"

          Write-Host "Deploying SSIS project to SSISDB..."

          & "C:\Program Files (x86)\Microsoft SQL Server\160\DTS\Binn\ISDeploymentWizard.exe" `
            /Silent `
            /ModelType:Project `
            /SourcePath:"$ISPAC_PATH" `
            /DestinationServer:"$DEPLOY_SERVER" `
            /DestinationPath:"SSISDB\$FOLDER_NAME\$PROJECT_NAME"

          if ($LASTEXITCODE -ne 0) {
            throw "SSIS deployment failed with exit code $LASTEXITCODE"
          }
