name: Automate SQL Server Database Creation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      sqlserver:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: P@ssw0rd123
          MSSQL_PID: Express
        ports:
          - 1433:1433
        options: --health-cmd "opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P P@ssw0rd123 -Q 'SELECT 1'" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SQLCMD
        run: |
          sudo apt-get update
          sudo apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Wait for SQL Server to be ready
        run: |
          for i in {1..30}; do
            /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U sa -P P@ssw0rd123 -Q "SELECT 1" && break
            echo "Waiting for SQL Server..."
            sleep 2
          done

      - name: Run SQL Script
        run: |
          /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U sa -P P@ssw0rd123 -i setup.sql

      - name: Verify Data
        run: |
          /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U Auto_user -P SecureP@ssw0rd123 -Q "SELECT * FROM AutoTest.dbo.user"
