name: Automate SQL Server Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  setup-sql:
    runs-on: ubuntu-latest # Base OS for Docker compatibility
    container:
      image: ubuntu:20.04 # Use a newer base image with compatible glibc
    steps:
      # Step 1: Install dependencies (sqlcmd and other tools)
      - name: Install prerequisites
        run: |
          apt-get update
          apt-get install -y curl gnupg
          curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
          apt-get update
          ACCEPT_EULA=Y apt-get install -y mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc

      # Step 2: Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Create Database, Stored Procedure, and Insert Data
      - name: Setup Database and Table
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }} # Pinggy URL
          SQL_USER: ${{ secrets.SQL_USER }}     # Auto_user
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }} # Password
        run: |
          # Ensure sqlcmd is in PATH
          export PATH="$PATH:/opt/mssql-tools/bin"
          
          # Create the SQL script
          cat << 'EOF' > setup.sql
          USE master;
          GO
          
          -- Create the database if it doesn't exist
          IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'AutoTest')
          BEGIN
              CREATE DATABASE AutoTest;
          END
          GO
          
          USE AutoTest;
          GO
          
          -- Create the stored procedure
          IF OBJECT_ID('dbo.SetupUserTable', 'P') IS NOT NULL
              DROP PROCEDURE dbo.SetupUserTable;
          GO
          
          CREATE PROCEDURE dbo.SetupUserTable
          AS
          BEGIN
              -- Create the user table if it doesn't exist
              IF NOT EXISTS (SELECT * FROM sys.tables WHERE name = 'user')
              BEGIN
                  CREATE TABLE [user] (
                      Name VARCHAR(50),
                      Surname VARCHAR(50),
                      Email VARCHAR(100)
                  );
              END
              
              -- Insert sample data
              INSERT INTO [user] (Name, Surname, Email)
              VALUES 
                  ('John', 'Doe', 'john.doe@example.com'),
                  ('Jane', 'Smith', 'jane.smith@example.com'),
                  ('Bob', 'Johnson', 'bob.johnson@example.com');
          END
          GO
          
          -- Execute the stored procedure
          EXEC dbo.SetupUserTable;
          GO
          EOF
          
          # Run the SQL script against the SQL Server
          sqlcmd -S "$SQL_SERVER" -U "$SQL_USER" -P "$SQL_PASSWORD" -i setup.sql -d master

      # Step 4: Verify the setup (optional)
      - name: Verify Table Creation
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        run: |
          export PATH="$PATH:/opt/mssql-tools/bin"
          sqlcmd -S "$SQL_SERVER" -U "$SQL_USER" -P "$SQL_PASSWORD" -Q "USE AutoTest; SELECT * FROM [user];" -d AutoTest
