name: SQL Server Automation

on:
  workflow_dispatch:

jobs:
  automate-sql:
    runs-on: docker-container
    container:
      image: mcr.microsoft.com/mssql-tools

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Wait for SQL Server to be ready
        run: |
          for i in {1..10}; do
            /opt/mssql-tools/bin/sqlcmd -S ${{ secrets.SQL_SERVER }} -U ${{ secrets.SQL_USER }} -P ${{ secrets.SQL_PASSWORD }} -Q "SELECT 1" && break
            sleep 5
          done

      - name: Create Database
        run: |
          /opt/mssql-tools/bin/sqlcmd -S ${{ secrets.SQL_SERVER }} -U ${{ secrets.SQL_USER }} -P ${{ secrets.SQL_PASSWORD }} -Q "IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = 'AutoTest') CREATE DATABASE AutoTest;"

      - name: Create Table
        run: |
          /opt/mssql-tools/bin/sqlcmd -S ${{ secrets.SQL_SERVER }} -U ${{ secrets.SQL_USER }} -P ${{ secrets.SQL_PASSWORD }} -d AutoTest -Q "CREATE TABLE [user] (Name NVARCHAR(50), Surname NVARCHAR(50), Email NVARCHAR(100));"

      - name: Create Stored Procedure
        run: |
          /opt/mssql-tools/bin/sqlcmd -S ${{ secrets.SQL_SERVER }} -U ${{ secrets.SQL_USER }} -P ${{ secrets.SQL_PASSWORD }} -d AutoTest -Q "CREATE PROCEDURE InsertUser @Name NVARCHAR(50), @Surname NVARCHAR(50), @Email NVARCHAR(100) AS BEGIN INSERT INTO [user] VALUES (@Name, @Surname, @Email); END;"

      - name: Insert Data Using Stored Procedure
        run: |
          /opt/mssql-tools/bin/sqlcmd -S ${{ secrets.SQL_SERVER }} -U ${{ secrets.SQL_USER }} -P ${{ secrets.SQL_PASSWORD }} -d AutoTest -Q "EXEC InsertUser 'Ongeziwe', 'Cwesi', 'ongeziwe@example.com';"
