name: Auto-create SQL Database with Pinggy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  create-database:
    runs-on: ubuntu-latest
    timeout-minutes: 10  # Give enough time for Pinggy connection
    steps:
      - name: Install SQL Tools
        run: |
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18 mssql-tools18
          echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
          source ~/.bashrc

      - name: Test Pinggy Connection
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        run: |
          echo "Testing connection to Pinggy tunnel..."
          /opt/mssql-tools18/bin/sqlcmd -S "$SQL_SERVER" -U "$SQL_USER" -P "$SQL_PASSWORD" -Q "SELECT 1" || exit 1

      - name: Create Database and Table
        env:
          SQL_SERVER: ${{ secrets.SQL_SERVER }}
          SQL_USER: ${{ secrets.SQL_USER }}
          SQL_PASSWORD: ${{ secrets.SQL_PASSWORD }}
        run: |
          /opt/mssql-tools18/bin/sqlcmd -S "$SQL_SERVER" -U "$SQL_USER" -P "$SQL_PASSWORD" -Q "CREATE DATABASE AutoTest"
          /opt/mssql-tools18/bin/sqlcmd -S "$SQL_SERVER" -U "$SQL_USER" -P "$SQL_PASSWORD" -d AutoTest -Q "
            CREATE TABLE [user] (
                Name NVARCHAR(100),
                Surname NVARCHAR(100),
                Email NVARCHAR(255)
            );
            CREATE PROCEDURE InsertUser
                @Name NVARCHAR(100),
                @Surname NVARCHAR(100),
                @Email NVARCHAR(255)
            AS
            BEGIN
                INSERT INTO [user] (Name, Surname, Email)
                VALUES (@Name, @Surname, @Email)
            END;
            EXEC InsertUser 'GitHub', 'Actions', 'github@example.com';
          "
