name: PR Approval Notification
 
on:
  pull_request_review:
    types: [submitted]
 
jobs:
  notify-teams:
    runs-on: ubuntu-latest
    steps:
      - name: Send message to Microsoft Teams
        run: |
          curl -H "Content-Type: application/json" -d '{
            "text": "🚀 Pull Request Approved! \nRepo: '${{ github.repository }}' \nPR: '${{ github.event.pull_request.html_url }}' \nApproved by: '${{ github.actor }}'"
          }' '${{ secrets.WEBHOOK_TEAMS_URL }}'
